from enum import Enum


class Discipline(Enum):
    ARCHEOLOGIA = 'archeologia'
    ARCHITEKTURA_I_URBANISTYKA = 'architektura i urbanistyka'
    ASTRONOMIA = 'astronomia'
    AUTOMATYKA_ELEKTRONIKA_I_ELEKTROTECHNIKA = 'automatyka, elektronika i elektrotechnika'
    EKONOMIA_I_FINANSE = 'ekonomia i finanse'
    FILOZOFIA = 'filozofia'
    GEOGRAFIA_SPOLECZNO_EKONOMICZNA_I_GOSPODARKA_PRZESTRZENNA = 'geografia społeczno-ekonomiczna i gospodarka przestrzenna'
    HISTORIA = 'historia'
    INFORMATYKA = 'informatyka'
    INFORMATYKA_TECHNICZNA_I_TELEKOMUNIKACJA = 'informatyka techniczna i telekomunikacja'
    INZYNIERIA_BIOMEDYCZNA = 'inżynieria biomedyczna'
    INZYNIERIA_CHEMICZNA = 'inżynieria chemiczna'
    INZYNIERIA_LADOWA_I_TRANSPORT = 'inżynieria lądowa i transport'
    INZYNIERIA_MATERIALOWA = 'inżynieria materiałowa'
    INZYNIERIA_MECHANICZNA = 'inżynieria mechaniczna'
    INZYNIERIA_SRODOWISKA_GORNICTWO_I_ENERGETYKA = 'inżynieria środowiska, górnictwo i energetyka'
    JEZYKOZNAWSTWO = 'językoznawstwo'
    MATEMATYKA = 'matematyka'
    LITERATUROZNAWSTWO = 'literaturoznawstwo'
    NAUKI_BIOLOGICZNE = 'nauki biologiczne'
    NAUKI_CHEMICZNE = 'nauki chemiczne'
    NAUKI_FIZYCZNE = 'nauki fizyczne'
    NAUKI_FARMACEUTYCZNE = 'nauki_farmaceutyczne'
    NAUKI_MEDYCZNE = 'nauki medyczne'
    NAUKI_O_BEZPIECZENSTWIE = 'nauki o bezpieczeństwie'
    NAUKI_O_KOMUNIKACJI_SPOLECZNEJ_I_MEDIACH = 'nauki o komunikacji społecznej i mediach'
    NAUKI_O_KULTURZE_FIZYCZNEJ = 'nauki o kulturze fizycznej'
    NAUKI_O_KULTURZE_I_RELIGII = 'nauki o kulturze i religii'
    NAUKI_O_POLITYCE_I_ADMINISTRACJI = 'nauki o polityce i administracji'
    NAUKI_O_SZTUCE = 'nauki o sztuce'
    NAUKI_O_ZARZADZANIU_I_JAKOSCI = 'nauki o zarządzaniu i jakości'
    NAUKI_O_ZDROWIU = 'nauki o zdrowiu'
    NAUKI_O_ZIEMI_I_SRODOWISKU = 'nauki o Ziemi i środowisku'
    NAUKI_PRAWNE = 'nauki prawne'
    NAUKI_SOCJOLOGICZNE = 'nauki socjologiczne'
    PEDAGOGIKA = 'pedagogika'
    PSYCHOLOGIA = 'psychologia'
    ROLNICTWO_I_OGRODNICTWO = 'rolnictwo i ogrodnictwo'

