from enum import Enum


class Discipline(Enum):
    ARCHEOLOGIA = 'dziedzina nauk humanistycznych / archeologia'
    ARCHITEKTURA_I_URBANISTYKA = 'dziedzina nauk inżynieryjno-technicznych / architektura i urbanistyka'
    ASTRONOMIA = 'dziedzina nauk ścisłych i przyrodniczych / astronomia'
    AUTOMATYKA_ELEKTRONIKA_I_ELEKTROTECHNIKA = 'dziedzina nauk inżynieryjno-technicznych / automatyka, elektronika i elektrotechnika'
    EKONOMIA_I_FINANSE = 'dziedzina nauk społecznych / ekonomia i finanse'
    FILOZOFIA = 'dziedzina nauk humanistycznych / filozofia'
    GEOGRAFIA_SPOLECZNO_EKONOMICZNA_I_GOSPODARKA_PRZESTRZENNA = 'dziedzina nauk społecznych / geografia społeczno-ekonomiczna i gospodarka przestrzenna'
    HISTORIA = 'dziedzina nauk humanistycznych / historia'
    INFORMATYKA = 'dziedzina nauk ścisłych i przyrodniczych / informatyka'
    INFORMATYKA_TECHNICZNA_I_TELEKOMUNIKACJA = 'dziedzina nauk inżynieryjno-technicznych / informatyka techniczna i telekomunikacja'
    INZYNIERIA_BIOMEDYCZNA = 'dziedzina nauk inżynieryjno-technicznych / inżynieria biomedyczna'
    INZYNIERIA_CHEMICZNA = 'dziedzina nauk inżynieryjno-technicznych / inżynieria chemiczna'
    INZYNIERIA_LADOWA_I_TRANSPORT = 'dziedzina nauk inżynieryjno-technicznych / inżynieria lądowa i transport'
    INZYNIERIA_MATERIALOWA = 'dziedzina nauk inżynieryjno-technicznych / inżynieria materiałowa'
    INZYNIERIA_MECHANICZNA = 'dziedzina nauk inżynieryjno-technicznych / inżynieria mechaniczna'
    INZYNIERIA_SRODOWISKA_GORNICTWO_I_ENERGETYKA = 'dziedzina nauk inżynieryjno-technicznych / inżynieria środowiska, górnictwo i energetyka'
    JEZYKOZNAWSTWO = 'dziedzina nauk humanistycznych / językoznawstwo'
    MATEMATYKA = 'dziedzina nauk ścisłych i przyrodniczych / matematyka'
    LITERATUROZNAWSTWO = 'dziedzina nauk humanistycznych / literaturoznawstwo'
    NAUKI_BIOLOGICZNE = 'dziedzina nauk ścisłych i przyrodniczych / nauki biologiczne'
    NAUKI_CHEMICZNE = 'dziedzina nauk ścisłych i przyrodniczych / nauki chemiczne'
    NAUKI_FIZYCZNE = 'dziedzina nauk ścisłych i przyrodniczych / nauki fizyczne'
    NAUKI_FARMACEUTYCZNE = 'dziedzina nauk medycznych i nauk o zdrowiu / nauki_farmaceutyczne'
    NAUKI_MEDYCZNE = 'dziedzina nauk medycznych i nauk o zdrowiu / nauki medyczne'
    NAUKI_O_BEZPIECZENSTWIE = 'dziedzina nauk społecznych / nauki o bezpieczeństwie'
    NAUKI_O_KOMUNIKACJI_SPOLECZNEJ_I_MEDIACH = 'dziedzina nauk społecznych / nauki o komunikacji społecznej i mediach'
    NAUKI_O_KULTURZE_FIZYCZNEJ = 'dziedzina nauk medycznych i nauk o zdrowiu / nauki o kulturze fizycznej'
    NAUKI_O_KULTURZE_I_RELIGII = 'dziedzina nauk humanistycznych / nauki o kulturze i religii'
    NAUKI_O_POLITYCE_I_ADMINISTRACJI = 'dziedzina nauk społecznych / nauki o polityce i administracji'
    NAUKI_O_SZTUCE = 'dziedzina nauk humanistycznych / nauki o sztuce'
    NAUKI_O_ZARZADZANIU_I_JAKOSCI = 'dziedzina nauk społecznych / nauki o zarządzaniu i jakości'
    NAUKI_O_ZDROWIU = 'dziedzina nauk medycznych i nauk o zdrowiu / nauki o zdrowiu'
    NAUKI_O_ZIEMI_I_SRODOWISKU = 'dziedzina nauk ścisłych i przyrodniczych / nauki o Ziemi i środowisku'
    NAUKI_PRAWNE = 'dziedzina nauk społecznych / nauki prawne'
    NAUKI_SOCJOLOGICZNE = 'dziedzina nauk społecznych / nauki socjologiczne'
    PEDAGOGIKA = 'dziedzina nauk społecznych / pedagogika'
    PSYCHOLOGIA = 'dziedzina nauk społecznych / psychologia'
    ROLNICTWO_I_OGRODNICTWO = 'dziedzina nauk rolniczych / rolnictwo i ogrodnictwo'

