export enum Position {
  PROFESOR_ZWYCZAJNY = 'profesor zwyczajny',
  DOKTORANT = 'doktorant',
  ADIUNKT = 'adiunkt',
  ASYSTENT = 'asystent',
  PROFESOR_NADZWYCZAJNY = 'profesor nadzwyczajny',
  PRACOWNIK_INZYNIERYJNO_TECHNICZNY = 'pracownik inżynieryjno-techniczny',
  EMERYT = 'emeryt',
  SPECJALISTA = 'specjalista',
  STARSZY_WYKLADOWCA = 'starszy wykładowca',
  ZATRUDNIENIE_W_RAMACH_GRANTU = 'zatrudnienie w ramach grantu',
  KUSTOSZ = 'kustosz',
  PRACOWNIK_NAUKOWO_TECHNICZNY = 'pracownik naukowo-techniczny',
  BIBLIOTEKARZ = 'bibliotekarz',
  STARSZY_KUSTOSZ_DYPLOMOWANY = 'starszy kustosz dyplomowany',
  WYKLADOWCA = 'wykładowca',
  PRACOWNIK_ADMINISTRACYJNY = 'pracownik administracyjny',
  STAZYSTA = 'stażysta',
  KUSTOSZ_DYPLOMOWANY = 'kustosz dyplomowany',
}
